modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId = "skinchangerapi"
version = "${file.jarVersion}"
displayName = "Skin Changer API"
description = '''Skin Changer API'''

[[dependencies.skinchangerapi]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skinchangerapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
